### ISSUE TITLE
Document new API process

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#30]
@neutrinog commented on [Fri Sep 01 2017](https://github.com/unfoldingWord-dev/door43.org/issues/692)

## Story

As a developer I want to read how all the API components fit together and what the chain of events are when content is added to the catalog.

**Comment by neutrinog** [comment]
I've updated the README to reflect the current implementation of the API pipeline.
Right now it's not merged in because it's on my branch of html updates. However here's the commit with documentation updates: https://github.com/neutrinog/d43-catalog/blob/d425a240a3ccfb948f3d3035afed38f5f3c5228f/README.md
